// Package ids provides the platform-wide identifier strategy.
//
// Aegis uses UUIDv7 identifiers (48-bit unix-millisecond timestamp +
// crypto-random entropy) as the single globally unique identifier strategy
// across all services and databases. UUIDv7 strings sort lexicographically
// in creation order (the same property ULIDs have) while remaining valid
// values for native UUID columns in PostgreSQL and ClickHouse.
package ids

import (
	"crypto/rand"
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
)

// New returns a new UUIDv7 string (canonical 36-char RFC 4122 form).
// Safe for concurrent use; identifiers generated by the same process sort
// in generation order (the v7 sequence counter is strictly monotonic
// within one millisecond).
func New() string {
	u, err := uuid.NewV7()
	if err != nil {
		panic("ids: crypto/rand unavailable: " + err.Error())
	}
	return u.String()
}

// NewAt returns a UUIDv7 string carrying the given timestamp as its
// embedded unix-millisecond time (used for seeds and backfilled records;
// the entropy bits remain random).
func NewAt(t time.Time) string {
	ms := t.UnixMilli()
	b := make([]byte, 16)
	if _, err := io.ReadFull(rand.Reader, b); err != nil {
		panic("ids: crypto/rand unavailable: " + err.Error())
	}
	b[0] = byte(ms >> 40)
	b[1] = byte(ms >> 32)
	b[2] = byte(ms >> 24)
	b[3] = byte(ms >> 16)
	b[4] = byte(ms >> 8)
	b[5] = byte(ms)
	b[6] = 0x70 | b[6]&0x0F // version 7
	b[8] = 0x80 | b[8]&0x3F // RFC 4122 variant
	u, err := uuid.FromBytes(b)
	if err != nil {
		panic("ids: " + err.Error())
	}
	return u.String()
}

// Valid reports whether s is a well-formed UUIDv7 identifier.
func Valid(s string) bool {
	u, err := uuid.Parse(s)
	return err == nil && u.Version() == 7
}

// Time extracts the embedded timestamp from a UUIDv7 identifier.
func Time(s string) (time.Time, error) {
	u, err := uuid.Parse(s)
	if err != nil {
		return time.Time{}, err
	}
	if u.Version() != 7 {
		return time.Time{}, fmt.Errorf("ids: %s is not a UUIDv7", s)
	}
	ms := int64(u[0])<<40 | int64(u[1])<<32 | int64(u[2])<<24 |
		int64(u[3])<<16 | int64(u[4])<<8 | int64(u[5])
	return time.UnixMilli(ms).UTC(), nil
}
